// Package golden предоставляет утилиты для тестирования сгенерированного кода
// с использованием golden-файлов (эталонов).
//
// Golden-файлы хранятся в testdata/ относительно тестируемого пакета.
// Для обновления эталонов используйте флаг -update:
//
//	go test ./... -update
package golden

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/go-mosaic/gomosaic/v2/pkg/gomosaic"
)

var update = flag.Bool("update", false, "обновить golden-файлы")

// AssertFile сравнивает GoFile с golden-файлом, включая package и imports.
func AssertFile(t *testing.T, f *gomosaic.GoFile, name string) {
	t.Helper()

	var buf bytes.Buffer
	if err := f.Render(&buf, "test"); err != nil {
		t.Fatalf("ошибка рендеринга: %v", err)
	}

	generated := normalizeCode(buf.Bytes())

	goldenPath := filepath.Join("fixtures", name+".golden")

	if *update {
		dir := filepath.Dir(goldenPath)
		if err := os.MkdirAll(dir, 0755); err != nil {
			t.Fatalf("не удалось создать директорию: %v", err)
		}
		if err := os.WriteFile(goldenPath, generated, 0644); err != nil {
			t.Fatalf("не удалось записать golden-файл: %v", err)
		}
		t.Logf("обновлён golden-файл: %s", goldenPath)
		return
	}

	expected, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("не удалось прочитать golden-файл %s: %v\nИспользуйте -update для создания", goldenPath, err)
	}

	expected = normalizeCode(expected)

	if !bytes.Equal(generated, expected) {
		diff := simpleDiff(string(expected), string(generated))
		t.Errorf("код отличается от эталона:\n%s", diff)
	}
}

// normalizeCode приводит код к единому формату для сравнения.
func normalizeCode(data []byte) []byte {
	lines := strings.Split(string(data), "\n")
	var result []string
	for _, line := range lines {
		// Пропускаем заголовок генерации (меняется от запуска к запуску)
		if strings.Contains(line, "Code generated by") ||
			strings.Contains(line, "DO NOT EDIT") ||
			strings.HasPrefix(strings.TrimSpace(line), "//go:build") {
			continue
		}
		// Убираем trailing whitespace
		result = append(result, strings.TrimRight(line, " \t"))
	}
	// Убираем пустые строки в конце
	for len(result) > 0 && strings.TrimSpace(result[len(result)-1]) == "" {
		result = result[:len(result)-1]
	}
	return []byte(strings.Join(result, "\n") + "\n")
}

// ParseAndGenerate парсит Go-файл с аннотациями и возвращает типы.
// file — путь к .go файлу с аннотациями относительно корня проекта.
func ParseAndGenerate(t *testing.T, dir, goFile string) (*gomosaic.ModuleInfo, []*gomosaic.NameTypeInfo) {
	t.Helper()

	// Получаем абсолютный путь к тестируемой директории
	absPath, err := filepath.Abs(filepath.Join(dir, goFile))
	if err != nil {
		t.Fatalf("filepath.Abs: %v", err)
	}

	// Ищем go.mod вверх по директориям от файла
	modDir := filepath.Dir(absPath)
	for {
		if _, err := os.Stat(filepath.Join(modDir, "go.mod")); err == nil {
			break
		}
		parent := filepath.Dir(modDir)
		if parent == modDir {
			t.Fatalf("не найден go.mod начиная с %s", filepath.Dir(absPath))
		}
		modDir = parent
	}

	module, err := gomosaic.LoadModuleInfo(filepath.Join(modDir, "go.mod"))
	if err != nil {
		t.Fatalf("LoadModuleInfo: %v", err)
	}

	// Парсим директорию с файлом напрямую (без go/packages для скорости)
	testDataDir := filepath.Dir(absPath)
	types, err := gomosaic.ParseDir(testDataDir)
	if err != nil {
		t.Fatalf("ParseDir(%s): %v", testDataDir, err)
	}
	if len(types) == 0 {
		t.Fatalf("ParseDir не нашёл типы в %s", testDataDir)
	}

	// Дополняем пути пакетов из модуля
	relPath, _ := filepath.Rel(modDir, testDataDir)
	for _, nt := range types {
		if nt.Package != nil && nt.Package.Path == "" {
			nt.Package.Path = filepath.Join(module.Path, relPath)
		}
	}

	return module, types
}

func simpleDiff(expected, actual string) string {
	expLines := strings.Split(expected, "\n")
	actLines := strings.Split(actual, "\n")

	var diff strings.Builder
	maxLen := len(expLines)
	if len(actLines) > maxLen {
		maxLen = len(actLines)
	}

	diffs := 0
	for i := 0; i < maxLen; i++ {
		var expLine, actLine string
		if i < len(expLines) {
			expLine = expLines[i]
		}
		if i < len(actLines) {
			actLine = actLines[i]
		}

		if expLine != actLine {
			if diffs < 20 { // Ограничиваем вывод
				diff.WriteString(fmt.Sprintf("  line %d:\n", i+1))
				if expLine != "" {
					diff.WriteString(fmt.Sprintf("    - %s\n", expLine))
				}
				if actLine != "" {
					diff.WriteString(fmt.Sprintf("    + %s\n", actLine))
				}
			}
			diffs++
		}
	}
	if diffs > 20 {
		diff.WriteString(fmt.Sprintf("  ... и ещё %d отличий\n", diffs-20))
	}
	return diff.String()
}
