name: golangci-lint
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.5

    - name: Run golangci-lint
      run: $(go env GOPATH)/bin/golangci-lint run